[package]
name = "blah-autoscale"
version = "0.1.0"
authors = ["Dennis Dietrich <d.dietrich84@gmail.com>"]

[dependencies]
log = "0.3"
env_logger = "0.3"
getopts = "0.2"
mio = "0.6"
hyper = "0.9"
url = "1.2"
rustc-serialize = "0.3"
httparse = "1.1"
