[package]
name = "blah-api-2"
version = "0.1.0"
authors = ["Dennis Dietrich <d.dietrich84@gmail.com>"]

[dependencies]
hyper = "0.9"
rustc-serialize = "0.3"
uuid = { version = "0.2", features = ["rustc-serialize", "v4"] }
kafka = "0.3"
