[package]
name = "autoscale-fut"
version = "0.1.0"
authors = ["Dennis Dietrich <d.dietrich84@gmail.com>"]

[dependencies]
curl = "0.3.6"
futures = "0.1"
tokio-core = "0.1"
tokio-curl = "0.1"
rustc-serialize = "0.3"
